# Generated by Django 3.0.6 on 2020-05-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='option2',
            field=models.CharField(max_length=40),
        ),
    ]
