# Generated by Django 3.0.6 on 2020-05-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20200528_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='option1_count',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option2_count',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option3_count',
            field=models.IntegerField(default=None),
        ),
    ]
